name: Macos build

on:
  workflow_dispatch:
    inputs:
      pythonSpec:
        description: 'Python spec'
        required: true

jobs:
  build:

    runs-on: macos-10.15  # macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

#    - run: pip install -U pip setuptools
    - run: |
        /usr/bin/python3 -mvenv .venv
        .venv/bin/pip install -U pip setuptools
        .venv/bin/pip install -e .
    - run: echo "${{ github.event.inputs.pythonSpec }}"
    - run: echo ${{ github.event.inputs.pythonSpec }}
    - run: echo {{ github.event.inputs.pythonSpec }}
