name: Macos build

on:
  workflow_dispatch:
    inputs:
      pythonSpec:
        description: 'Python spec'
        required: true

jobs:
  build:

    runs-on: macos-10.15  # macos-11

    steps:
    - uses: actions/checkout@v2
    - run: |
        /usr/bin/python3 -mvenv .venv
        .venv/bin/pip install -U pip setuptools
        .venv/bin/pip install -e .
    - run: .venv/bin/portable-python build "${{ github.event.inputs.pythonSpec }}"
    - uses: actions/upload-artifact@v2
      with:
        path: dist/
        retention-days: 2
        if-no-files-found: error
